/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package budget.budgetproject;

/**
 *
 * @author ale
 */



public class DefinitionFrame extends javax.swing.JFrame {
    //Connect/Get definition class
    TermDefinition definitions = new TermDefinition();
    //Text-wrap for the definition label, otherwise it'll go off the screen
    final String html = "<html><body style='width: %1spx'>%1s";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DefinitionFrame.class.getName());

    

    
    public DefinitionFrame() {

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JButton();
        DefinitionButtonsArea = new javax.swing.JPanel();
        BalanceButton = new javax.swing.JButton();
        BudgetButton = new javax.swing.JButton();
        CategoryButton = new javax.swing.JButton();
        EarningButton = new javax.swing.JButton();
        SpendingButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DefinitionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DashboardButton.setText("Go Back To Dashboard");
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(DashboardButton)
                .addGap(20, 20, 20))
        );

        DefinitionButtonsArea.setBackground(new java.awt.Color(204, 204, 204));

        BalanceButton.setText("Balance");
        BalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceButtonActionPerformed(evt);
            }
        });

        BudgetButton.setText("Budget");
        BudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BudgetButtonActionPerformed(evt);
            }
        });

        CategoryButton.setText("Category");
        CategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryButtonActionPerformed(evt);
            }
        });

        EarningButton.setText("Earning");
        EarningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarningButtonActionPerformed(evt);
            }
        });

        SpendingButton.setText("Spending");
        SpendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpendingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DefinitionButtonsAreaLayout = new javax.swing.GroupLayout(DefinitionButtonsArea);
        DefinitionButtonsArea.setLayout(DefinitionButtonsAreaLayout);
        DefinitionButtonsAreaLayout.setHorizontalGroup(
            DefinitionButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefinitionButtonsAreaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(DefinitionButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpendingButton)
                    .addComponent(EarningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        DefinitionButtonsAreaLayout.setVerticalGroup(
            DefinitionButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefinitionButtonsAreaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(BalanceButton)
                .addGap(43, 43, 43)
                .addComponent(BudgetButton)
                .addGap(43, 43, 43)
                .addComponent(CategoryButton)
                .addGap(46, 46, 46)
                .addComponent(EarningButton)
                .addGap(47, 47, 47)
                .addComponent(SpendingButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DefinitionLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DefinitionLabel.setText("Definition: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(DefinitionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(DefinitionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DefinitionButtonsArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DefinitionButtonsArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void BalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Set "Definition:" to the definition of word; Note the 340 is the length of the line (used for word-wrap)
        DefinitionLabel.setText(String.format(html, 340, "Definition of Balance: " + definitions.getBalanceDefinition()));
    }                                             

    private void BudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Set "Definition:" to the definition of word
        DefinitionLabel.setText(String.format(html, 340, "Definition of Budget: " + definitions.getBudgetDefinition()));
    }                                            

    private void CategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Set "Definition:" to the definition of word
        DefinitionLabel.setText(String.format(html, 340, "Definition of Category: " + definitions.getCategoryDefinition()));
    }                                              

    private void EarningButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Set "Definition:" to the definition of word
        DefinitionLabel.setText(String.format(html, 340, "Definition of Earning: " + definitions.getEarningDefinition()));
    }                                             

    private void SpendingButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Set "Definition:" to the definition of word
        DefinitionLabel.setText(String.format(html, 340, "Definition of Spending: " + definitions.getSpendingDefinition()));
    }                                              

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
       /* "DashboardFrame" might change names to match the current frame name, maybe it's MainApp or just DashboardFrame, but here's the layout: */
        //Close current definition frame
        dispose(); 
    }                                               

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton BalanceButton;
    private javax.swing.JButton BudgetButton;
    private javax.swing.JButton CategoryButton;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JPanel DefinitionButtonsArea;
    private javax.swing.JLabel DefinitionLabel;
    private javax.swing.JButton EarningButton;
    private javax.swing.JButton SpendingButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel navbar;
    // End of variables declaration                   
}