/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package budget.budgetproject;


import java.io.*;
import java.util.*;
/**
 *
 * @author ryanfahmy
 */

public class TransactionHistoryFrame extends javax.swing.JFrame {
    private Login login;
    private ArrayList<Transaction> transactions;
    /**
     * Creates new form TransactionHistoryFrame
     */
    public TransactionHistoryFrame(Login login,javax.swing.JFrame parent) {
        super("Transaction History");
        this.login = login;
        transactions = new ArrayList<>(getTransactions(login.getData()));
        initComponents();
        setSize(500,300);
        
        setLocationRelativeTo(null);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        categoryField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EarningsField = new javax.swing.JTextField();
        TransactionHistory = new javax.swing.JComboBox<>();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Amount:");
        jPanel1.add(jLabel1);

        amountField.setEditable(false);
        if (!transactions.isEmpty()) {
            amountField.setText(Double.toString(transactions.get(0).getAmount()));
        }
        else
        amountField.setText("");
        jPanel1.add(amountField);

        jLabel2.setText("Category:");
        jPanel1.add(jLabel2);

        categoryField.setEditable(false);
        if (!transactions.isEmpty())
        categoryField.setText(transactions.get(0).getCategory());
        else
        categoryField.setText("");
        jPanel1.add(categoryField);

        jLabel3.setText("Date Created:");
        jPanel1.add(jLabel3);

        dateField.setEditable(false);
        if (!transactions.isEmpty())
        dateField.setText(transactions.get(0).getDate().toString().substring(0,10));
        else
        dateField.setText("");
        jPanel1.add(dateField);

        jLabel4.setText("Earnings/Spending:");
        jPanel1.add(jLabel4);

        EarningsField.setEditable(false);
        if (!transactions.isEmpty())
        EarningsField.setText(transactions.get(0).getisEarnings() ? "Earning" : "Spending");
        else
        EarningsField.setText("");
        EarningsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarningsFieldActionPerformed(evt);
            }
        });
        jPanel1.add(EarningsField);

        TransactionHistory.setModel(new javax.swing.DefaultComboBoxModel(transactions.toArray()));
        TransactionHistory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TransactionHistoryItemStateChanged(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void TransactionHistoryItemStateChanged(java.awt.event.ItemEvent evt) {                                                    
            if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) { //execute if an item was selected
                Transaction transaction = transactions.get(TransactionHistory.getSelectedIndex()); //get selected transaction
                System.out.printf("%d %d %s %n",TransactionHistory.getSelectedIndex(),TransactionHistory.getItemCount(),TransactionHistory.getSelectedItem());
                amountField.setText(Double.toString(transaction.getAmount())); //set amount
                categoryField.setText(transaction.getCategory()); //set category
                dateField.setText(transaction.getDate().toString().substring(0,10)); //set date
                EarningsField.setText(transaction.getisEarnings() ? "Earning" : "Spending");
            }
            
    }                                                   

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
    }                                        

    private void EarningsFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param data
     * @return something
     */
    
    public static final ArrayList<Transaction> getTransactions(File data) { //get Transactions
        CategorySelector selector = new CategorySelector();
        ArrayList<Transaction> transactions = new ArrayList<>(); //list of transactions
        try {
            Scanner scandata = new Scanner(data);
            while (scandata.hasNextLine()) { //read data from file
                String nextLine = scandata.nextLine();
                if (nextLine.startsWith("Transaction")) { //Take data from lines that start with transaction
                   String[] lineList = nextLine.split(","); //Separate lines based on commas
                   Date date = new Date(Integer.parseInt(lineList[1]), //set date
                           Integer.parseInt(lineList[2]),Integer.parseInt(lineList[3]));
                   Double amount = Double.parseDouble(lineList[7]); //set amount
                   String category = selector.getAllCategories()[Integer.parseInt
                    (lineList[6].substring(8))-1]; //set category
                   Boolean isEarnings = (lineList[5].equals("Earning"));
                   transactions.add(new Transaction(date,amount,category,isEarnings)); //add transaction to list of transactions
                   
                }
            }
        }
        catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        }
       return transactions;
        
    }


    // Variables declaration - do not modify                     
    private javax.swing.JTextField EarningsField;
    private javax.swing.JComboBox<String> TransactionHistory;
    private javax.swing.JTextField amountField;
    private javax.swing.JTextField categoryField;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
